[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Sec-Fetch-Site = "same-origin"
    Content-Security-Policy = "upgrade-insecure-requests"
    Feature-Policy = '''
    accelerometer 'none';
    ambient-light-sensor 'none';
    autoplay 'none';
    battery 'none';
    camera 'none';
    display-capture 'none';
    document-domain 'none';
    encrypted-media 'none';
    web-share 'self';
    microphone 'none';
    geolocation 'none';
    '''
